-- Seed Nabil's accounts
-- NOTE: Replace 'NABIL_USER_ID' with the actual UUID after Nabil logs in
-- For now, these are inserted without assigned_to (will be assigned on first login)

insert into accounts (name, sector) values
  ('AMMPS', 'Public'),
  ('Protection civile', 'Public'),
  ('HACA', 'Régulation'),
  ('ANRE', 'Énergie'),
  ('TAX', 'Finance'),
  ('Ministère chargé de l''environnement', 'Public'),
  ('BKAM', 'Finance'),
  ('MHPV', 'Public'),
  ('CH Ibn Sina', 'Santé'),
  ('UPF', 'Éducation'),
  ('Ministère de la santé', 'Public'),
  ('Diana Holding', 'Industrie'),
  ('ONSSA', 'Public'),
  ('MICEPP', 'Public'),
  ('GCAM', 'Finance'),
  ('ACOME', 'Industrie'),
  ('ACWA POWER', 'Énergie'),
  ('AMAZON', 'Tech'),
  ('ANEP', 'Public'),
  ('APTIV', 'Automobile'),
  ('AUDA', 'Public'),
  ('BANK AL-MAGHRIB', 'Finance'),
  ('BOA SERVICES', 'Finance'),
  ('CAC', 'Public'),
  ('CDG PREVOYANCE', 'Finance'),
  ('CREDIT AGRICOLE DU MAROC', 'Finance'),
  ('Direction Provinciale de la Justice Oujda', 'Public'),
  ('FCZ', 'Industrie'),
  ('FILTER SYSTEMS', 'Industrie'),
  ('HUIR', 'Industrie'),
  ('INWI', 'Telecom'),
  ('JET CONTRACTORS', 'BTP'),
  ('Jet Energy', 'Énergie'),
  ('Administration des Douanes et Impôts Indirects', 'Public'),
  ('LEAR', 'Automobile'),
  ('LOBAMO', 'Industrie'),
  ('LYDEC', 'Utilities'),
  ('MAROC LEASING', 'Finance'),
  ('MEDI 1 RADIO', 'Média'),
  ('MEDI 1 TV', 'Média'),
  ('NOMAC', 'Énergie'),
  ('OCP GROUP', 'Industrie'),
  ('ONCF', 'Transport'),
  ('PLASTICUM', 'Industrie'),
  ('PREMO', 'Industrie'),
  ('SAFIEC', 'Industrie'),
  ('SEW EURODRIVE', 'Industrie'),
  ('SII SERVICES MAROC', 'Tech'),
  ('SNOP TANGER', 'Automobile'),
  ('TAQA MOROCCO', 'Énergie'),
  ('TE CONNECTIVITY', 'Tech'),
  ('TIKTOK', 'Tech'),
  ('TLAIDI TECHNOLOGIE', 'Tech'),
  ('UIR', 'Éducation'),
  ('UMAN', 'Tech'),
  ('UNIVERSITE SETTAT', 'Éducation')
on conflict do nothing;
